function [part,objval] = METIS_PartGraphRecursive(nvtxs,ncon,...
                                    xadj,adjncy,vwgt,vsize,adjwgt,...
                                    nparts,tpwgts,ubvec,options)
xadj = xadj-1;
adjncy = adjncy-1;
[objval,part] = METIS_PartGraphRecursive_mex(nvtxs,ncon,...
                            xadj,adjncy,vwgt,vsize,adjwgt,...
                            nparts,tpwgts,ubvec,options);

end